# -*- coding: utf-8 -*-

match_req_code = (
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import '../providers/api_provider.dart';\n"
    "import '../core/theme/app_theme.dart';\n"
    "\n"
    "class AddMatchRequestScreen extends ConsumerStatefulWidget {\n"
    "  const AddMatchRequestScreen({super.key});\n"
    "  @override\n"
    "  ConsumerState<AddMatchRequestScreen> createState() => _AddMatchRequestScreenState();\n"
    "}\n"
    "\n"
    "class _AddMatchRequestScreenState extends ConsumerState<AddMatchRequestScreen> {\n"
    "  final _titleCtrl = TextEditingController();\n"
    "  final _descCtrl = TextEditingController();\n"
    "  final _spotsCtrl = TextEditingController();\n"
    "  final _costCtrl = TextEditingController();\n"
    "  DateTime _selectedDate = DateTime.now().add(const Duration(days: 1));\n"
    "  TimeOfDay _selectedTime = const TimeOfDay(hour: 20, minute: 0);\n"
    "  bool _isLoading = false;\n"
    "\n"
    "  Future<void> _pickDateTime() async {\n"
    "    final date = await showDatePicker(\n"
    "      context: context,\n"
    "      initialDate: _selectedDate,\n"
    "      firstDate: DateTime.now(),\n"
    "      lastDate: DateTime.now().add(const Duration(days: 30)),\n"
    "      builder: (context, child) => Theme(\n"
    "        data: ThemeData.dark().copyWith(\n"
    "          colorScheme: const ColorScheme.dark(primary: AppTheme.neonBlue, onPrimary: Colors.black, surface: AppTheme.surfaceDark),\n"
    "        ),\n"
    "        child: child!,\n"
    "      ),\n"
    "    );\n"
    "    if (date != null) {\n"
    "      if (!mounted) return;\n"
    "      final time = await showTimePicker(\n"
    "        context: context,\n"
    "        initialTime: _selectedTime,\n"
    "        builder: (context, child) => Theme(\n"
    "          data: ThemeData.dark().copyWith(\n"
    "            colorScheme: const ColorScheme.dark(primary: AppTheme.neonBlue, onPrimary: Colors.black, surface: AppTheme.surfaceDark),\n"
    "          ),\n"
    "          child: child!,\n"
    "        ),\n"
    "      );\n"
    "      if (time != null) {\n"
    "        setState(() {\n"
    "          _selectedDate = DateTime(date.year, date.month, date.day, time.hour, time.minute);\n"
    "          _selectedTime = time;\n"
    "        });\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "\n"
    "  Future<void> _submit() async {\n"
    "    if (_titleCtrl.text.isEmpty || _spotsCtrl.text.isEmpty || _costCtrl.text.isEmpty) {\n"
    "      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('\u0627\u0644\u0631\u062c\u0627\u0621 \u0645\u0644\u0621 \u062c\u0645\u064a\u0639 \u0627\u0644\u062d\u0642\u0648\u0644 \u0627\u0644\u0645\u0637\u0644\u0648\u0628\u0629')));\n"
    "      return;\n"
    "    }\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      final payload = {\n"
    "        'title': _titleCtrl.text,\n"
    "        'description': _descCtrl.text,\n"
    "        'matchTime': _selectedDate.toUtc().toIso8601String(),\n"
    "        'missingSpots': int.parse(_spotsCtrl.text),\n"
    "        'costPerSpot': double.parse(_costCtrl.text),\n"
    "      };\n"
    "      await ref.read(dioProvider).post('/match-requests', data: payload);\n"
    "      ref.refresh(matchRequestsProvider.future);\n"
    "      if (mounted) {\n"
    "        Navigator.pop(context);\n"
    "        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('\u062a\u0645 \u0625\u0646\u0634\u0627\u0621 \u0637\u0644\u0628 \u0627\u0644\u0645\u0628\u0627\u0631\u0627\u0629 \u0628\u0646\u062c\u0627\u062d!')));\n"
    "      }\n"
    "    } catch (e) {\n"
    "      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('\u062e\u0637\u0623: \$e')));\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Scaffold(\n"
    "      appBar: AppBar(\n"
    "        title: const Text('\u0625\u0646\u0634\u0627\u0621 \u0637\u0644\u0628 \u0646\u0627\u0642\u0635\u0646\u064a \u0644\u0627\u0639\u0628'),\n"
    "        backgroundColor: AppTheme.surfaceDark,\n"
    "        foregroundColor: Colors.white,\n"
    "      ),\n"
    "      body: SingleChildScrollView(\n"
    "        padding: const EdgeInsets.all(24),\n"
    "        child: Column(\n"
    "          crossAxisAlignment: CrossAxisAlignment.stretch,\n"
    "          children: [\n"
    "            const Text('\u0647\u0644 \u0641\u0631\u064a\u0642\u0643 \u0646\u0627\u0642\u0635 \u0644\u0627\u0639\u0628\u064a\u0646\u061f \u0627\u0643\u062a\u0628 \u0627\u0644\u062a\u0641\u0627\u0635\u064a\u0644 \u0647\u0646\u0627 \u0648\u0633\u064a\u062a\u0645\u0643\u0646 \u0628\u0627\u0642\u064a \u0627\u0644\u0644\u0627\u0639\u0628\u064a\u0646 \u0645\u0646 \u0627\u0644\u0627\u0646\u0636\u0645\u0627\u0645 \u0644\u0643.',\n"
    "              style: TextStyle(color: Colors.white70, fontSize: 16)),\n"
    "            const SizedBox(height: 24),\n"
    "            TextField(\n"
    "              controller: _titleCtrl,\n"
    "              style: const TextStyle(color: Colors.white),\n"
    "              decoration: InputDecoration(\n"
    "                labelText: '\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0637\u0644\u0628',\n"
    "                labelStyle: const TextStyle(color: Colors.white54),\n"
    "                filled: true, fillColor: AppTheme.surfaceDark,\n"
    "                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 16),\n"
    "            TextField(\n"
    "              controller: _descCtrl,\n"
    "              maxLines: 3,\n"
    "              style: const TextStyle(color: Colors.white),\n"
    "              decoration: InputDecoration(\n"
    "                labelText: '\u062a\u0641\u0627\u0635\u064a\u0644 \u0625\u0636\u0627\u0641\u064a\u0629',\n"
    "                labelStyle: const TextStyle(color: Colors.white54),\n"
    "                filled: true, fillColor: AppTheme.surfaceDark,\n"
    "                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 16),\n"
    "            Row(\n"
    "              children: [\n"
    "                Expanded(\n"
    "                  child: TextField(\n"
    "                    controller: _spotsCtrl,\n"
    "                    keyboardType: TextInputType.number,\n"
    "                    style: const TextStyle(color: Colors.white),\n"
    "                    decoration: InputDecoration(\n"
    "                      labelText: '\u0639\u062f\u062f \u0627\u0644\u0644\u0627\u0639\u0628\u064a\u0646 \u0627\u0644\u0645\u0637\u0644\u0648\u0628',\n"
    "                      labelStyle: const TextStyle(color: Colors.white54),\n"
    "                      filled: true, fillColor: AppTheme.surfaceDark,\n"
    "                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),\n"
    "                    ),\n"
    "                  ),\n"
    "                ),\n"
    "                const SizedBox(width: 16),\n"
    "                Expanded(\n"
    "                  child: TextField(\n"
    "                    controller: _costCtrl,\n"
    "                    keyboardType: TextInputType.number,\n"
    "                    style: const TextStyle(color: Colors.white),\n"
    "                    decoration: InputDecoration(\n"
    "                      labelText: '\u062a\u0643\u0644\u0641\u0629 \u0627\u0644\u0641\u0631\u062f (\u062c.\u0645)',\n"
    "                      labelStyle: const TextStyle(color: Colors.white54),\n"
    "                      filled: true, fillColor: AppTheme.surfaceDark,\n"
    "                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),\n"
    "                    ),\n"
    "                  ),\n"
    "                ),\n"
    "              ],\n"
    "            ),\n"
    "            const SizedBox(height: 24),\n"
    "            OutlinedButton.icon(\n"
    "              onPressed: _pickDateTime,\n"
    "              icon: const Icon(Icons.calendar_month, color: AppTheme.neonBlue),\n"
    "              label: Text('\u0645\u0648\u0639\u062f \u0627\u0644\u0645\u0628\u0627\u0631\u0627\u0629: \${_selectedDate.year}-\${_selectedDate.month}-\${_selectedDate.day}',\n"
    "                style: const TextStyle(color: Colors.white)),\n"
    "              style: OutlinedButton.styleFrom(\n"
    "                padding: const EdgeInsets.symmetric(vertical: 16),\n"
    "                side: const BorderSide(color: AppTheme.neonBlue),\n"
    "                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 32),\n"
    "            ElevatedButton(\n"
    "              onPressed: _isLoading ? null : _submit,\n"
    "              style: ElevatedButton.styleFrom(\n"
    "                backgroundColor: AppTheme.neonBlue,\n"
    "                foregroundColor: Colors.white,\n"
    "                minimumSize: const Size.fromHeight(55),\n"
    "                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "              child: _isLoading\n"
    "                ? const CircularProgressIndicator(color: Colors.white)\n"
    "                : const Text('\u0646\u0634\u0631 \u0627\u0644\u0637\u0644\u0628', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),\n"
    "            ),\n"
    "          ],\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

edit_profile_code = (
    "import 'dart:io';\n"
    "import 'package:flutter/material.dart';\n"
    "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
    "import 'package:image_picker/image_picker.dart';\n"
    "import 'package:dio/dio.dart';\n"
    "import '../providers/api_provider.dart';\n"
    "import '../core/theme/app_theme.dart';\n"
    "\n"
    "class EditProfileScreen extends ConsumerStatefulWidget {\n"
    "  const EditProfileScreen({super.key});\n"
    "  @override\n"
    "  ConsumerState<EditProfileScreen> createState() => _EditProfileScreenState();\n"
    "}\n"
    "\n"
    "class _EditProfileScreenState extends ConsumerState<EditProfileScreen> {\n"
    "  late TextEditingController _nameCtrl;\n"
    "  late TextEditingController _phoneCtrl;\n"
    "  XFile? _selectedImage;\n"
    "  bool _isLoading = false;\n"
    "\n"
    "  @override\n"
    "  void initState() {\n"
    "    super.initState();\n"
    "    final user = ref.read(currentUserProvider);\n"
    "    _nameCtrl = TextEditingController(text: user?['name'] ?? '');\n"
    "    _phoneCtrl = TextEditingController(text: user?['phone'] ?? '');\n"
    "  }\n"
    "\n"
    "  Future<void> _pickImage() async {\n"
    "    final picker = ImagePicker();\n"
    "    final image = await picker.pickImage(source: ImageSource.gallery);\n"
    "    if (image != null) setState(() => _selectedImage = image);\n"
    "  }\n"
    "\n"
    "  Future<void> _submit() async {\n"
    "    setState(() => _isLoading = true);\n"
    "    try {\n"
    "      final dio = ref.read(dioProvider);\n"
    "      String? profilePicUrl;\n"
    "      if (_selectedImage != null) {\n"
    "        final formData = FormData.fromMap({\n"
    "          'images': await MultipartFile.fromFile(_selectedImage!.path),\n"
    "        });\n"
    "        final uploadRes = await dio.post('/upload', data: formData);\n"
    "        final images = List<String>.from(uploadRes.data['images']);\n"
    "        if (images.isNotEmpty) profilePicUrl = images[0];\n"
    "      }\n"
    "      final payload = {'name': _nameCtrl.text, 'phone': _phoneCtrl.text};\n"
    "      if (profilePicUrl != null) payload['profilePic'] = profilePicUrl;\n"
    "      final res = await dio.put('/users/me', data: payload);\n"
    "      ref.read(currentUserProvider.notifier).state = res.data;\n"
    "      if (mounted) {\n"
    "        Navigator.pop(context);\n"
    "        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('\u062a\u0645 \u062a\u062d\u062f\u064a\u062b \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u0634\u062e\u0635\u064a \u0628\u0646\u062c\u0627\u062d')));\n"
    "      }\n"
    "    } catch (e) {\n"
    "      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('\u062e\u0637\u0623: \$e')));\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    final user = ref.watch(currentUserProvider);\n"
    "    final currentPic = user?['profilePic'];\n"
    "    return Scaffold(\n"
    "      appBar: AppBar(\n"
    "        title: const Text('\u062a\u0639\u062f\u064a\u0644 \u0627\u0644\u0645\u0644\u0641 \u0627\u0644\u0634\u062e\u0635\u064a'),\n"
    "        backgroundColor: AppTheme.surfaceDark,\n"
    "        foregroundColor: Colors.white,\n"
    "      ),\n"
    "      body: SingleChildScrollView(\n"
    "        padding: const EdgeInsets.all(24),\n"
    "        child: Column(\n"
    "          children: [\n"
    "            GestureDetector(\n"
    "              onTap: _pickImage,\n"
    "              child: Stack(\n"
    "                alignment: Alignment.bottomRight,\n"
    "                children: [\n"
    "                  CircleAvatar(\n"
    "                    radius: 60,\n"
    "                    backgroundColor: AppTheme.surfaceLighter,\n"
    "                    backgroundImage: _selectedImage != null\n"
    "                        ? FileImage(File(_selectedImage!.path)) as ImageProvider\n"
    "                        : (currentPic != null ? NetworkImage(currentPic) : null),\n"
    "                    child: (_selectedImage == null && currentPic == null)\n"
    "                        ? const Icon(Icons.person, size: 60, color: Colors.white54)\n"
    "                        : null,\n"
    "                  ),\n"
    "                  Container(\n"
    "                    padding: const EdgeInsets.all(8),\n"
    "                    decoration: const BoxDecoration(color: AppTheme.neonBlue, shape: BoxShape.circle),\n"
    "                    child: const Icon(Icons.camera_alt, color: Colors.black, size: 20),\n"
    "                  ),\n"
    "                ],\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 32),\n"
    "            TextField(\n"
    "              controller: _nameCtrl,\n"
    "              style: const TextStyle(color: Colors.white),\n"
    "              decoration: InputDecoration(\n"
    "                labelText: '\u0627\u0644\u0627\u0633\u0645',\n"
    "                labelStyle: const TextStyle(color: Colors.white54),\n"
    "                filled: true, fillColor: AppTheme.surfaceDark,\n"
    "                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 16),\n"
    "            TextField(\n"
    "              controller: _phoneCtrl,\n"
    "              style: const TextStyle(color: Colors.white),\n"
    "              keyboardType: TextInputType.phone,\n"
    "              decoration: InputDecoration(\n"
    "                labelText: '\u0631\u0642\u0645 \u0627\u0644\u0647\u0627\u062a\u0641',\n"
    "                labelStyle: const TextStyle(color: Colors.white54),\n"
    "                filled: true, fillColor: AppTheme.surfaceDark,\n"
    "                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 32),\n"
    "            ElevatedButton(\n"
    "              onPressed: _isLoading ? null : _submit,\n"
    "              style: ElevatedButton.styleFrom(\n"
    "                backgroundColor: AppTheme.neonBlue,\n"
    "                foregroundColor: Colors.white,\n"
    "                minimumSize: const Size.fromHeight(55),\n"
    "                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),\n"
    "              ),\n"
    "              child: _isLoading\n"
    "                ? const CircularProgressIndicator(color: Colors.white)\n"
    "                : const Text('\u062d\u0641\u0638 \u0627\u0644\u062a\u0639\u062f\u064a\u0644\u0627\u062a', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),\n"
    "            ),\n"
    "          ],\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

with open('mobile-app/lib/screens/add_match_request_screen.dart', 'w', encoding='utf-8', newline='\n') as f:
    f.write(match_req_code)

with open('mobile-app/lib/screens/edit_profile_screen.dart', 'w', encoding='utf-8', newline='\n') as f:
    f.write(edit_profile_code)

print("Done - both files written cleanly with unicode escapes")
